### ISSUE TITLE
Adding tests that mimic eventstreams

### ISSUE THREAD

**Issue by halfAbee** [fsprojects/FSharp.Desktop.UI#11]
I'd like to test the GUI I have built by writing scripts that generate the EventStreams that your mvc controllers dispatch on.

If I have a mousewheel event defined as:

w.MouseWheel |> Observable.map (fun args -> if args.Delta > 0 then Next else Previous)

I'd like to be generating the "Next" or "Previous" events in my integration tests rather than using the real MouseWheel (but still exercising the rest of the real GUI).

I haven't a good idea how to plumb that in; I've tried a few things that didn't really work.

Please would you give a few pointers on how to get started?

Thanks,

George.

**Comment by dmitry-a-morozov** [comment]
I apologize for really delayed response - I was in "holiday" mode.
I covered unit testing a little bit in my series. 
https://github.com/dmitry-a-morozov/fsharp-wpf-mvc-series/wiki/Controller#unit-testing
(only replace ```EventHandler``` with ```Dispacher```)
Strong separation of concerns is key to this library architecture. Most often you'll be interesting in testing controller functionality. It's completely decoupled from infrastructure components like WPF and RX. Basically you only need invoke ```Controller.Dispatch myevent mymodel``` and assert that model properly mutated. There is a little value in integration testing of all 3 MVC components. 

There are rare cases when you might want to test a view logic. This will be typical for complex event transformations or data bindings. In this case you can consider manual testing/eyeballing because both binding logic and event transformation are fairly declarative and have little room for repeatable mistakes. Or you can do something like "Window driver" http://martinfowler.com/eaaDev/WindowDriver.html  by simulation user action and testing events or data bindings.

**Comment by halfAbee** [comment]
No problem, it was more an issue of also learning Rx better, which I managed to do.

I agree about unit testing, and it is a great feature of your design. For my use case, I was also looking to automatically driving quite a complicated GUI so that I could eyeball its live behavior; more of an acceptance or "play" testing thing. And I learned how to do it in principle by getting better at Rx inside your current `EventStreams` list, e.g., at one stage I was stuck thinking how does one ignore some events, until I learned the following idiom:
```
 w.PreviewKeyDown
      |> Observable.map
        (fun args ->
          match args.Key with
          | Key.R -> Some Random
          | Key.S -> Some Submit
          | _     -> None
        )
      |> Observable.choose id
```
(where `Random` and `Submit `are some events handled by the controller, the point being I don't have to worry about the `None` case, because of the `choose`).

My acceptance tests could just be some arbitrarily complex custom `EventStreams` list. For the moment I just have some extra "high level" or "compound" user level events corresponding to acceptance tests implemented directly via the controller, which served their purpose; I'll be able to do it differently next time.

**Comment by halfAbee** [comment]
Thanks, but it turns out the lacking part for me was my knowledge of Rx, which I've since improved. I agree about unit testing, and your framework is great for supporting that. I was also looking at automatically driving quite a complicated GUI so that I could eyeball the live behaviour, which is more of an acceptance or "play" testing scenario. 

My ease with using Rx with your framework much improved when I started learning idioms like the following; how do you ignore some user generated events in the `EventStreams` list?
```
  w.PreviewKeyDown
      |> Observable.map
         (fun args ->
            match args.Key with
            | Key.R -> Some Random
            | Key.S -> Some Submit
            | _     -> None
         )
      |> Observable.choose id
```
The important thing here is that we don't have to deal with the `None` case in the controller, since it is filtered out by `choose`. I was still learning that kind of thing when I asked my question.

With my improving Rx and MVC knowledge, it has become clearer to me that I could implement acceptance tests by creating custom `EventStreams` list generators, perhaps specified by a little DSL built on top of the MVC event DUs. Meanwhile, I've already implemented some fixed high level compound events via the controller to do the acceptance/play testing; but I now have an acceptance testing approach to try next time.

**Comment by dmitry-a-morozov** [comment]
Sounds good. 
To me the easiest way to generate IObservable streams in tests is to use ```ToObsevable``` combinator. http://msdn.microsoft.com/en-us/library/hh212140
Also you can define "knobs" on a view to drive testing process. It's similar to "knobs" on ```StopWatchObservable``` type I used in chapter 11 of the series.
https://github.com/dmitry-a-morozov/fsharp-wpf-mvc-series/wiki/External-Event-Sources 
Source is here
https://github.com/dmitry-a-morozov/fsharp-wpf-mvc-series/blob/master/Chapter%2011%20-%20Composition%20-%20external%20event%20sources/Composition%20-%20external%20event%20sources/StopWatchObservable.fs

BTW, do you think it will be convenient to have pre-defined method ```Trigger``` or ```Push``` on concrete base [View] (https://github.com/fsprojects/FSharp.Desktop.UI/blob/master/src/View.fs#L24) to enable such scenarios?
