### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by wezeku** [fsprojects/FSharp.Desktop.UI#18]
When using the NuGet package, I get this exception when calling `Model.Create()`:

    Message: An unhandled exception of type 'System.TypeInitializationException' occurred in Prog.exe
    Additional information: The type initializer for 'FSharp.Desktop.UI.Model' threw an exception.

If I upgrade Castle.Core to the latest version, `Model.Create()` works. So, it seems that the Castle.Core version referenced in the NuGet package doesn't work with the latest version of .NET or F# runtime.

**Comment by wastaz** [comment]
It would be nice to have an updated nuget package. I didn't get the problem with Castle.Core that wezeku got, but I would very much like to use the `BindingOperations` stuff. That doesn't seem to be part of the latest nuget release (0.7) but if I pull down the code and compile it it's there.

**Comment by dmitry-a-morozov** [comment]
Can you send a PR?

**Comment by wastaz** [comment]
For building a new nuget package?
No, I don't think I can. You are the only one with the proper nuget api key that can build such a package.

**Comment by dmitry-a-morozov** [comment]
Done. Ver 0.7.1
