### ISSUE TITLE
Can't access the documentation page

### ISSUE THREAD

**Issue by peng1999** [fsprojects/FSharp.Desktop.UI#19]
Access to [the documentation(http://fsprojects.github.io/FSharp.Desktop.UI/)](http://fsprojects.github.io/FSharp.Desktop.UI/) returns a 404 error.

**Comment by dmitry-a-morozov** [comment]
@forki  @sergey-tihon Hey Paket/Fake magicians I need your help. Currently build including docs generation fails with "generate.fsx(28,1): error FS0084: Assembly reference '../../packages/Microsoft.AspNet.Razor/lib/net40/System.Web.Razor.dll' was not found or is invalid"
I tried my best but cannot resolve it.

**Comment by tehcrashxor** [comment]
Until this is fixed, we can use Archive.org's copy: https://web.archive.org/web/20150429204822/http://fsprojects.github.io/FSharp.Desktop.UI/
