### ISSUE TITLE
Rx-Main package is unlisted

### ISSUE THREAD

**Issue by odytrice** [fsprojects/FSharp.Desktop.UI#26]
### Description
This project depends on Rx-Main and the package is now unlisted. Should be changed to System.Reactive.*

**Comment by travis-leith** [comment]
Why is no-one accepting this pull request? Seems like a no brainer.

**Comment by odytrice** [comment]
I think this project has been abandoned ☹️ It would be nice if ownership was transferred to someone who is willing to continue managing it

**Comment by odytrice** [comment]
This project for all intents and purposes is dead.

**Comment by travis-leith** [comment]
Have you looked at [Fabulous](https://github.com/fsprojects/Fabulous)?
Looks very promising, can be used in the same way as FSharp.Desktop.Ui (that is with static Xaml), and can also be used to generate dynamic xaml.
